name: Install Dependencies & Build
on: [push, pull_request]

jobs:
  install-and-build:
    name: Install Dependencies & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'LavaMoat/lavamoat-webpack'
          ref: ''
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: ''
          path: ''
          clean: ''
          fetch-depth: ''
          lfs: ''
      - name: Install Dependencies
        run: yarn 
      - name: Build 
        run: yarn lavamoat