name: CI
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # will run `yarn install` command
      - uses: borales/actions-yarn@v2.0.2
        with:
          cmd: install
      # will run `yarn lint` command
      - uses: borales/actions-yarn@v2.0.2
        with:
          cmd: lint
      # will run `yarn test` command
      - uses: borales/actions-yarn@v2.0.2
        with:
          cmd: test
